# So that we can test __m128's alignment
stack-align-test-flags += -msse

CFLAGS-.o += -Wa,-mtune=i686
CFLAGS-.o_shared += -Wa,-mtune=i686
CFLAGS-.op += -Wa,-mtune=i686
CFLAGS-.o_static += -Wa,-mtune=i686

ASFLAGS-.o += -Wa,-mtune=i686
ASFLAGS-.o_shared += -Wa,-mtune=i686
ASFLAGS-.op += -Wa,-mtune=i686
ASFLAGS-.o_static += -Wa,-mtune=i686
